### ISSUE TITLE
Update the module to Tres v4

### ISSUE THREAD

**Issue by oumarbarry** [Tresjs/nuxt#105]
### Description

Updating ` "@tresjs/core": "3.9.0" ` to **4.0.2**
and maybe ` "three": "^0.164.1" ` and ` "@types/three": "^0.164.0" ` to **0.165.0** too

### Validations

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.

**Comment by oumarbarry** [comment]
@alvarosabu, any insights about merging #104 ?

**Comment by HoppGwyn** [comment]
Also awaiting this, excited to try out the new version! Looks like its just waiting approval?

**Comment by gwynhokkers** [comment]
Also awaiting this, excited to try out the new version! Looks like its just waiting approval?

**Comment by alvarosabu** [comment]
Hi @oumarbarry @gwynhokkers we were waiting for some bug fixes on the core regarding primitives but, to unblock you guys, I will try to have it merged this week.
