### ISSUE TITLE
Nuxtjs: OrbitControls.js encountered an unknown camera type

### ISSUE THREAD

**Issue by HuakunShen** [Tresjs/nuxt#49]
### Describe the bug

I added OrbitControls, and when scrolling I get the following error

```
WARNING: OrbitControls.js encountered an unknown camera type - dolly/zoom disabled.
```

Make it impossible to scroll to zoom in/out. 

![image](https://github.com/Tresjs/tres/assets/33727687/9edd0b10-bae2-4ed9-a463-e3a9ef87c893)

### Reproduction

https://stackblitz.com/edit/nuxt-starter-3nnslu?file=package.json

### System Info

```shell
See https://stackblitz.com/edit/nuxt-starter-3nnslu?file=package.json
```

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by alvarosabu** [comment]
Potentially fixed by #47

**Comment by alvarosabu** [comment]
Reproduction [link](https://stackblitz.com/edit/nuxt-starter-3nnslu?file=nuxt.config.ts) is using v1.1.9 so it's still an issue.

**Comment by alvarosabu** [comment]
Seems like it only happens in dev mode, similar issue on R3F . @HuakunShen when you `build` and `preview` the error is gone 🤔

**Comment by alvarosabu** [comment]
Possible work-around is to import anything from three in your project.

```
import { Vector3 } from 'three'
```

That seems to force the deduping of three, I will try to find a better solution

**Comment by HuakunShen** [comment]
> Possible work-around is to import anything from three in your project.
> 
> ```
> import { Vector3 } from 'three'
> ```
> 
> That seems to force the deduping of three, I will try to find a better solution

@alvarosabu Import something from 'three' doesn't seem to work. But in production mode it works fine.

**Comment by alvarosabu** [comment]
@HuakunShen are you sure? https://stackblitz.com/edit/nuxt-starter-mt4nkb?file=app.vue

**Comment by HuakunShen** [comment]
> @HuakunShen are you sure? https://stackblitz.com/edit/nuxt-starter-mt4nkb?file=app.vue

It is weird. I did line by line comparison, the bug may come from `lang="ts"`.

In the example you provide, if you add `lang="ts"` to script, and remove `node_modules` and reinstall dependencies. It should reproduce the error.

**Comment by alvarosabu** [comment]
I'm afraid typescript has nothing to do with the actual issue.

**Comment by alvarosabu** [comment]
Is a duplicate on three imports

**Comment by HuakunShen** [comment]
@alvarosabu Right, when i use typescript I see a warning of duplicate three imports.

In my own app, if I remove typescript from the component, the problem is solved. But no idea why this happens. Still hope there is a proper fix.

**Comment by HuakunShen** [comment]
@alvarosabu The problem seems to be gone. The same reproduction https://stackblitz.com/edit/nuxt-starter-3nnslu?file=package.json works in development mode. I didn't upgrade any package.
