### ISSUE TITLE
TresCanvas doesn't render in Dynamicly loaded components or deeply nested components

### ISSUE THREAD

**Issue by RGaskinLtd** [Tresjs/nuxt#79]
### Describe the bug

I am trying to use a TresCanvas that is known to work when using in a staticly declared way
but if I use it in a component that is dynamicly loaded using 

`defineAsyncComponent(() => import('@/components/pageBuilder/component.vue'))`

it doesn't render the canvas the most I can get is the following

`<div window-size="" clear-color="#241246" shadows="" data-v-3789b801=""><canvas style=""></canvas></div>`

## Recent findings

just having the TresCanvas in a component that is nested 2 levels deep doesn't work.
no idea why or what is causing this. 

I've provided a reproduction of this

### Reproduction

https://stackblitz.com/edit/tresjs-basic-z2g8yk?file=src%2Fcomponents%2FTheExperience.vue

### Used Package Manager

npm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by userquin** [comment]
why using Vite in teh reproduction? this repo is about Nuxt

**Comment by RGaskinLtd** [comment]
that was the default setup that was provided to me. when creating a ticket

**Comment by alvarosabu** [comment]
Hi @RGaskinLtd your reproduction wasn't working because you missed the import `import { defineAsyncComponent } from 'vue';` (The console log warned about it)

Here is working https://stackblitz.com/edit/tresjs-basic-ffcbq9?file=src%2Fcomponents%2FTheExperience.vue

Next time please open the ticket on the correspondent repo since this has nothing to do with Nuxt. Thanks!
